baseurl             = "http://docs.blokks.dev:3000/"
title               = "Blokks documentation"
staticdir           = "static-compiled"
languageCode        = "en-us"
googleAnalytics     = "UA-123-45"

[params]
version             = "1.0.0"
