baseurl             = "http://localhost:3000/"
title               = "Blokks documentation"
staticdir           = "static-compiled"
languageCode        = "en-us"

[params]
analytics           = "UA-123-45"
author              = "@BlokksHQ"
version             = "1.0.0"
