baseurl             = "https://blokks.co/docs"
title               = "Blokks documentation"
staticdir           = ".static"
layoutdir           = ".layouts"
languageCode        = "en-us"

[params]
analytics           = "UA-64372736-2"
author              = "@BlokksHQ"
version             = "1.0.0"

[[menu.main]]
identifier = "getting-started"
name = "Getting started"
weight = 2

[[menu.main]]
identifier = "manage-your-schedule"
name = "Manage your schedule"
weight = 3

[[menu.main]]
identifier = "embed-your-schedule"
name = "Embed your schedule"
weight = 4

[[menu.main]]
identifier = "customize-your-embed"
name = "Customize your embed"
weight = 5

[[menu.main]]
identifier = "advanced-options"
name = "Advanced options"
weight = 6

[[menu.main]]
identifier = "custom-themes"
name = "Custom themes"
weight = 7

[[menu.main]]
identifier = "compatibility"
name = "Compatibility"
weight = 8

[[menu.main]]
identifier = "account-settings"
name = "Account settings"
weight = 9
