baseurl             = "https://blokks.co/docs"
title               = "Blokks documentation"
staticdir           = "static-compiled"
languageCode        = "en-us"

[params]
analytics           = "UA-64372736-2"
author              = "@BlokksHQ"
version             = "1.0.0"
