baseurl             = "https://blokks.co/docs"
title               = "Blokks documentation"
staticdir           = ".static"
layoutdir           = ".layouts"
languageCode        = "en-us"
SectionPagesMenu    = "main"

[params]
analytics           = "UA-64372736-2"
author              = "@BlokksHQ"
version             = "1.0.0"
